# Generated by Django 3.1.6 on 2021-02-10 12:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Data created on', verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Data modified on', verbose_name='Modified by')),
                ('mode', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Trash', 'Trash')], default='Active', max_length=30, verbose_name='Mode')),
                ('name', models.CharField(help_text='Category name', max_length=255, verbose_name='Category Name')),
                ('created_by', models.ForeignKey(editable=False, help_text='Data created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ecomm_category_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Data modified by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_ecomm_category_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Data created on', verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Data modified on', verbose_name='Modified by')),
                ('mode', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Trash', 'Trash')], default='Active', max_length=30, verbose_name='Mode')),
                ('name', models.CharField(help_text='Product name', max_length=255, verbose_name='Products Name')),
                ('description', models.TextField(blank=True, help_text='Product Description', verbose_name='Product Description')),
                ('mrp', models.FloatField(help_text='MRP', verbose_name='MRP')),
                ('sale_price', models.FloatField(help_text='Sale Price', verbose_name='Sale Price')),
                ('image', models.FileField(blank=True, null=True, upload_to='product_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'pdf'])], verbose_name='product_image')),
                ('category', models.ForeignKey(help_text='Category', on_delete=django.db.models.deletion.DO_NOTHING, to='ecomm.category')),
                ('created_by', models.ForeignKey(editable=False, help_text='Data created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ecomm_product_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Data modified by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_ecomm_product_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('store', models.ForeignKey(help_text='Store', on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='accounts.store')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Data created on', verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Data modified on', verbose_name='Modified by')),
                ('mode', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Trash', 'Trash')], default='Active', max_length=30, verbose_name='Mode')),
                ('line_items', models.TextField(help_text='Line Items', verbose_name='Line Items')),
                ('created_by', models.ForeignKey(editable=False, help_text='Data created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ecomm_order_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Data modified by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_ecomm_order_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Data created on', verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Data modified on', verbose_name='Modified by')),
                ('mode', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Trash', 'Trash')], default='Active', max_length=30, verbose_name='Mode')),
                ('line_items', models.TextField(help_text='Line Items', verbose_name='Line Items')),
                ('created_by', models.ForeignKey(editable=False, help_text='Data created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ecomm_cart_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Data modified by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_ecomm_cart_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart',
                'db_table': 'cart',
            },
        ),
    ]
