# Generated by Django 3.1.6 on 2021-02-10 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Data created on', verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Data modified on', verbose_name='Modified by')),
                ('mode', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Trash', 'Trash')], default='Active', max_length=30, verbose_name='Mode')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone Number', max_length=128, region=None, unique=True, verbose_name='Phone')),
                ('first_name', models.CharField(help_text='First name', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='Last name', max_length=255, verbose_name='Last Name')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff user?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is superuser?')),
                ('otp', models.IntegerField(blank=True, null=True, verbose_name='OTP')),
                ('created_by', models.ForeignKey(editable=False, help_text='Data created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Data modified by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_accounts_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Data created on', verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Data modified on', verbose_name='Modified by')),
                ('mode', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Trash', 'Trash')], default='Active', max_length=30, verbose_name='Mode')),
                ('name', models.CharField(help_text='Country name', max_length=100, unique=True, verbose_name='Name')),
                ('iso', models.CharField(help_text='2 letter country code (Example: US for United States)', max_length=2, unique=True)),
                ('iso3', models.CharField(help_text='3 letter country code (Example: US for United States)', max_length=3, unique=True)),
                ('calling_code', models.CharField(help_text='Telephone calling code (Example: +1 for United States)', max_length=10, verbose_name='Calling code')),
                ('created_by', models.ForeignKey(editable=False, help_text='Data created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts_country_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Data modified by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_accounts_country_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'country',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Data created on', verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Data modified on', verbose_name='Modified by')),
                ('mode', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Trash', 'Trash')], default='Active', max_length=30, verbose_name='Mode')),
                ('name', models.CharField(help_text='Store name', max_length=255, verbose_name='Store Name')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('address', models.TextField(blank=True, help_text='Address', verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, help_text='postal code', max_length=20, verbose_name='Postal Code')),
                ('created_by', models.ForeignKey(editable=False, help_text='Data created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts_store_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Data modified by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_accounts_store_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Data created on', verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Data modified on', verbose_name='Modified by')),
                ('mode', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Trash', 'Trash')], default='Active', max_length=30, verbose_name='Mode')),
                ('name', models.CharField(help_text='State name', max_length=100, verbose_name='Name')),
                ('abbreviation', models.CharField(blank=True, help_text='State abbreviation', max_length=30, verbose_name='Abbreviation')),
                ('country', models.ForeignKey(help_text='Country', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='accounts.country')),
                ('created_by', models.ForeignKey(editable=False, help_text='Data created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts_state_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Data modified by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_accounts_state_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'state',
                'ordering': ('name',),
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Data created on', verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Data modified on', verbose_name='Modified by')),
                ('mode', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Trash', 'Trash')], default='Active', max_length=30, verbose_name='Mode')),
                ('name', models.CharField(help_text='User role name', max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='User role description', verbose_name='Description')),
                ('created_by', models.ForeignKey(editable=False, help_text='Data created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts_role_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Data modified by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_accounts_role_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Data created on', verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Data modified on', verbose_name='Modified by')),
                ('mode', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Trash', 'Trash')], default='Active', max_length=30, verbose_name='Mode')),
                ('type', models.CharField(choices=[('Store', 'Store'), ('Home', 'Store'), ('Work', 'Work'), ('Other', 'Other')], default='Home', max_length=30, verbose_name='Type')),
                ('address_line1', models.CharField(blank=True, help_text='Address line 1', max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, help_text='Address line 2', max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, help_text='postal code', max_length=20, verbose_name='Postal Code')),
                ('country', models.ForeignKey(help_text='Country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', to='accounts.country', verbose_name='Country')),
                ('created_by', models.ForeignKey(editable=False, help_text='Data created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts_address_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Data modified by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_accounts_address_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('state', models.ForeignKey(help_text='State', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', to='accounts.state', verbose_name='State/Province/County')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
                'db_table': 'address',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(help_text='Role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
